version: "3.9"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"                 # open Redis on your laptop at port 6379
    command: ["redis-server", "--appendonly", "yes"]  # keep data after restarts
    volumes:
      - redis_data:/data            # store Redis data outside the container

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: chainlytics    # db username
      POSTGRES_PASSWORD: chainlytics# db password
      POSTGRES_DB: chainlytics      # default db name
    ports:
      - "5432:5432"                 # open Postgres on your laptop at port 5432
    volumes:
      - pg_data:/var/lib/postgresql/data  # store Postgres data persistently
      - ./infra/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql


volumes:
  redis_data:
  pg_data:
