version: "3.9"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

  postgres_raw:
    image: postgres:16
    environment:
      POSTGRES_USER: chainlytics
      POSTGRES_PASSWORD: chainlytics
      POSTGRES_DB: raw_db
    ports:
      - "5433:5432"
    volumes:
      - pg_raw_data:/var/lib/postgresql/data
      - ./infra/init_db_raw.sql:/docker-entrypoint-initdb.d/init_db_raw.sql

  postgres_analytics:
    image: postgres:16
    environment:
      POSTGRES_USER: chainlytics
      POSTGRES_PASSWORD: chainlytics
      POSTGRES_DB: analytics_db
    ports:
      - "5434:5432"
    volumes:
      - pg_analytics_data:/var/lib/postgresql/data
      - ./infra/init_db_analytics.sql:/docker-entrypoint-initdb.d/init_db_analytics.sql

volumes:
  redis_data:
  pg_raw_data:
  pg_analytics_data:
